### ISSUE TITLE
Keep track of records for users to refer back to 

### ISSUE THREAD

**Issue by sckott** [ropensci/spocc#108]
from #103 , the proposition from carl 

> I wonder if there's also a way to capture a reference back to the database source for each row. e.g. if you discover a particular row is an outlier in some way and want to see what is going on, it would be useful to call up the full entry information. Currently the only provenance is the source database.

some we can use their provided unique id, others we'd have to generate one

**Comment by sckott** [comment]
@cboettig playing with this locally...Is this the scenario in which you think these are useful:

- User calls `occ(...)` getting data from one or more data sources
- User then binds data together via `occ2df()` to a single data.frame
- User notices a few occurrences (aka rows) that they want to dig into further

What now?   Once I add occurrence IDs to the default output of `occ2df()` (or UUIDs or equiv for sources that don't provide unique IDs), then they can just subset the original data pulled back from the `occ()` result using those IDs. Do we need to automate that for users with another function, or just demo how to subset the original data returned from `occ()` call?

In some data sources in spocc its possible to get more data associated with each occurrence from the API via the pkg (e.g., rgbif). Users could then call whatever fxn is needed from the source to get further info. I suppose where this is possible, we'd want to make that easier for users by wrapping that in a single fxn interface like `occ()`.

**Comment by cboettig** [comment]
@sckott Good questions here, just taking a stab at possible strategy:

1. I think there's lots of scope for a helper function in helping users make sense of the additional data from occ.  One reason is just to help with the subsetting -- dplyr commands are nice and quick but when you have to work around the NSE to get them to work programmatically I'm finding that a helper function is handy (maybe I'm missing something, but e.g. in fishbase: https://github.com/ropensci/rfishbase/blob/38acaa31a6ed85e889ac3211cbff9291896022ff/R/species_list.R#L59-69).  The other role would just be to tidy up the occ returned data frame such that columns have the appropriate class, potentially more semantically meaningful column names, and filtering out any columns that aren't likely to be of any use in the process.   


2.  Whether the `occ()` should return all everything that might be useful for investigating outliers or whether the user should call some extra function that has to make another API call should be invisible to the users anyway.  I suppose one might save bandwidth by doing this as a second call rather than getting lots of extra info that will just be discarded, but I don't think that kind of thing matters much.

**Comment by sckott** [comment]
okay, got occurrence keys included in the output of `occ2df()`, and uuid's assigned to sources that don't provide keys: ecoengine. 

for ecoengine, there's nothing to reference back to unless we cache the results of the output of the `occ()` call locally on the users machine.  if we do cache, the whole object returned from `occ()` could be cached, and we can allow query back to that blob

for other sources, the occurrence keys are in the provider's DB, so we can make additional queries back to the DB  -  

this will require more thinking about what additional data is avail via each data provider _beyond what we already pull down in the `occ()` call_ given that we have an occurrence key

A potential workflow:

User:

* searches via `occ()`
* combines data to single data.frame via `occ2df()`
* inspects data, and wants to find out more info about one or more occurrences
* uses a to be provided (aka in the future) function to query for more information on each occurrence
    * some providers may not give any more further info over and above what we already pull down -> in this case call the queried output from `occ()`
    * some providers do provide addt'n info above what we pull down -> make query to their API 
    * combine lcoal and web API outputs to single object, with print method, etc.

**Comment by sckott** [comment]
this is done, i think, closing
