### ISSUE TITLE
Wildcards and Redundancy

### ISSUE THREAD

**Issue by bw4sz** [ropensci/spocc#137]
Hey @sckott,

I just updated my repos that use rgbif to use the spocc package. I'm very excited to hear about idigbio integration.

I'm searching for several flower genera - is there an explicit way to denote that i'm looking for a rank="Genus", or using a wildcard like "Penstemon *" to enforce genus status. Once i start to scale up, i want to build in some protections. It may not be needed?

Have you given any thought to redundancy in these datasets? Is this something i should be worried about? I imagine that many of the herbarium that contribute to gbif also contributes to idigbio. Maybe a filter for long + lat on the same date? Just a thought.

Are you planning on integrating the national phenology network package into spocc, or should i query separately. I'm trying to get a feel for what kind of time series data there are flowering species by combining herbarium/current data and how sampling effort has changed over time.

Thanks!

**Comment by sckott** [comment]
hey @bw4sz - thanks for your message. 

idigbio integration isn't quite there yet - i should be able to do it now, was waiting on fixes to the R client, which is now up on cran https://cran.rstudio.com/web/packages/ridigbio/ issues #136  #124 

> I'm searching for several flower genera - is there an explicit way to denote that i'm looking for a rank="Genus", or using a wildcard like "Penstemon *" to enforce genus status. Once i start to scale up, i want to build in some protections. It may not be needed?

Unfortunately, were subject to the various ways that search works in the many APIs we work with in `spocc`.  So the way we're approaching this is to pass options to each of the data sources e.g., via parameters  `gbifopts`, `vertnetopts`, etc.  Each source allows different kinds of queries and different modifiers via additional parameters. You can see what options are available via the `occ_options()` function.  I should make it more clear what parameter is being used in each data source for the name passed in to `occ()` #138 

An alternative approach is to first search for the exact taxon identifiers you want with the taxize package, then pass those to `occ()`. Only some of the data sources are supported right now though :( - but more will be supported soon.  

> Have you given any thought to redundancy in these datasets? Is this something i should be worried about? I imagine that many of the herbarium that contribute to gbif also contributes to idigbio. Maybe a filter for long + lat on the same date? Just a thought.

Yes. That stuff will be done in the new package `spoccutils`, including map functionality.  If you have any thoughts on this topic, that repo is the place to go https://github.com/ropensci/spoccutils see the `clean()` function https://github.com/ropensci/spoccutils/blob/master/R/clean.R - it doesn't do much yet. It's a tough problem.  Only need to worry about it when using more than 1 data source (e.g., gbif + vertnet) - but we still need to solve the problem of course.  We started a deduplication as a web service project at a recent hackathon https://github.com/idigbio-api-hackathon/dedup - but I don't think that will get finished. So that leaves local work in R to fix dups.  I think there will be some easy things we can do and some harder, which will likely require user input, but hopefully not so everything can be automated/reproducible.  

> Are you planning on integrating the national phenology network package into spocc, or should i query separately. I'm trying to get a feel for what kind of time series data there are flowering species by combining herbarium/current data and how sampling effort has changed over time.

yeah, i played with this, but there isn't alot of NPN data in different locations, which makes sense that there's good data through time in individual locations - which I think doesn't really fit with the theme of `spocc`, which focuses on getting species occurrence data - to answer your question, yes, Id suggest using it separately
