### ISSUE TITLE
an idigbio eg erroring

### ISSUE THREAD

**Issue by sckott** [ropensci/spocc#180]
```r
library(spocc)
wkt <- 'POLYGON((-98.9 44.2,-89.1 36.6,-116.7 37.5,-102.5 39.6,-98.9 44.2))'
occ(from = "idigbio", geometry = wkt, limit = 10)
#> Searched: idigbio
#> Occurrences - Found: 0, Returned: 0
#> Search type: Geometry
#> Warning message:
#> In foo_idigbio(sources, x, y, s, z, hc, w, idigbioopts) : HTTP failure: 400
#> Error message from API server: {"error":"Terms not found in index for type records","statusCode":400,"name":"TermNotFoundError","terms":["min_x","min_y","max_x","max_y"]}
```

see https://github.com/idigbio/idigbio-search-api/wiki/Query-Format#geographic-point-fields

need to change to doing 

```
{
  "geopoint": {
    "type": "geo_bounding_box",
    "top_left": {
      "lat": 19.23,
      "lon": -130
    },
    "bottom_right": {
      "lat": -45.1119,
      "lon": 179.99999
    }
  }
}
```

**Comment by Cactusolo** [comment]
Hi,

I got the same error:
# > tt <- occ(geometry = site.range[[1]][1], from = c("gbif", "idigbio", "inat"), has_coords=TRUE)
# Warning messages:
#   1: idigbio:  
#   2: idigbio: HTTP failure: 400
# Error message from API server: {"error":"Terms not found in index for type records","statusCode":400,"name":"TermNotFoundError","terms":["geopoint.1"]} 

Is it possible that "spocc" have a function to convert wkt format polygon into the right format to "idigbio"? otherwise "occ" loose the meaning being integrative with all these different databases?



BTW, inaturalist seems can not recognize terms of "Tracheophyta"  and "Magnoliophyta' etc?

Thanks!
